@startuml
title Diagrama de Atividade - Gerenciar Sala (Virtual)

|Administrador|
start
:Acessar painel de salas virtuais;
if (Qual ação deseja realizar?) then (Vincular Nova URL)
  :Digitar o endereço da sala virtual (Link);
  :Confirmar comando de salvamento;
  
  |Sistema|
  if (A URL informada é inválida?) then (Sim)
    :Exibir mensagem de formato de link incorreto;
  else (Não)
    :Gravar atributo urlSalaVirtual no banco de dados;
    :Exibir mensagem de link vinculado com sucesso;
  endif

else (Alterar Status de Disponibilidade)
  |Administrador|
  :Modificar chave de ativação da sala;
  :Confirmar alteração de status;
  
  |Sistema|
  :Atualizar atributo statusDisponibilidade na base;
  :Exibir mensagem de status da sala atualizado;
endif

|Sistema|
stop
@enduml