@startuml

class API_CEHAP {
    - usuariosDoSistema: List<UsuarioDoSistema>
    - autenticarUsuario(usuario: UsuarioDoSistema): Boolean
    - verificaSenha(senha: String): Boolean
    - guardarSenha(senha: String): Boolean
}

class UsuarioDoSistema {
    - emailInstitucional: String
    - senha: String
    - senhaPendente: Boolean
}

interface Requerente {
    + abrirChamado(motivo: String, mensagemInicial: String, urgencia: Urgencia, setorDestino: Setor): void
    + atualizarStatusChamado(chamado: Chamado, novoStatus: Status): void
    + encerrarChamado(chamado: Chamado): void
}

interface Requerido {
    + buscarChamados(): List<Chamado>
    + filtrarChamados(campo: String, valor: String): List<Chamado>
}

class ComportamentoRequerente implements Requerente {
    + abrirChamado(motivo: String, mensagemInicial: String, urgencia: Urgencia, setorDestino: Setor): void
    + atualizarStatusChamado(chamado: Chamado, novoStatus: Status): void
    + encerrarChamado(chamado: Chamado): void
}

class ComportamentoRequerido implements Requerido {
    + buscarChamados(): List<Chamado>
    + filtrarChamados(campo: String, valor: String): List<Chamado>
}

class Administrador extends UsuarioDoSistema implements Requerente, Requerido {
    - comportamentoRequerente: Requerente {readonly}
    - comportamentoRequerido: Requerido {readonly}
    + bloquearUsuario(usuario: UsuarioDoSistema): void
    + redefinirSenha(usuario: UsuarioDoSistema, novaSenha: String): void
    + buscarUsuarios(): List<UsuarioDoSistema>
}

class Gestor extends UsuarioDoSistema implements Requerente, Requerido {
    - comportamentoRequerente: Requerente {readonly}
    - comportamentoRequerido: Requerido {readonly}
    - setorGerido: Setor
    + buscarChamadosdoSetor(): List<Chamado>
}

class Setor {
    - nome: String
    - usuariosDoSetor: List<UsuarioDoSistema>
}

class Chamado {
    - motivo: String
    - urgencia: Urgencia
    - mensagemInicial: String
    - status: Status
    - setorDestino: Setor
    - usuarioRequerido: UsuarioRequerido
    - usuarioRequerente: UsuarioRequerente
    - chat: Chat
    + realizarTriagem(): UsuarioRequerido
    - notificarUsuarioRequerido(): void
}

enum Status {
    ABERTO
    EM_ANDAMENTO
    FECHADO
}

enum Urgencia {
    BAIXA
    MEDIA
    ALTA
}

class Chat {
    - mensagens: List<Mensagem>
    - participantes: List<UsuarioDoSistema>
    + enviarMensagem(mensagem: Mensagem): void
    + enviarAnexo(anexo: Anexo): void
    + exibirMensagens(): void
}

class Mensagem {
    - conteudo: String
    - remetente: UsuarioDoSistema
    - dataEnvio: Date
}

@enduml