@startuml

' Configurações estéticas para melhorar o layout e o direcionamento das setas
skinparam backgroundcolor #FFFFFF
skinparam packageStyle rect
skinparam ranksep 100
skinparam nodesep 30
left to right direction


' Definição dos Atores e Hierarquia
actor "Usuário do Sistema" as US
actor "Administrador" as Admin
actor "Usuário Comum" as UC
actor "Usuário Requerente" as UReq
actor "Usuário Requerido" as URec
actor "Gestor" as Gestor


US <|-- Admin
Admin -[hidden]down-> UC
US <|-- UC
UC <|-- UReq
UC <|-- URec
UC <|-- Gestor


' Autenticação e Segurança
package "Autenticação e Segurança" as P_Segurança{
    usecase (Login) as UC_Login
    usecase (Definir Senha) as UC_DefinirSenha
    usecase (Redefinir Credenciais) as UC_RedefinirCredenciais
    usecase (Gerenciar Acessos) as UC_GerenciarAcessos
    usecase (Vizualizar logs de acesso) as UC_Auditarlogs
}

package "Comunicação e Chamados" as P_Comunicação {
    usecase (Trocar Mensagens) as UC_TrocarMensagens
    usecase (Consultar Histórico de Chats) as UC_Historico
    usecase (Iniciar Chat Direto) as UC_ChatDireto
    usecase (Abrir Chamado) as UC_AbrirChamado
    usecase (Encerrar Chamado) as UC_EncerrarChamado
    usecase (Visualizar Filas de Chamados) as UC_VisualizarFilas

    ' Agrupando as extensões para apontarem na mesma direção
    UC_Historico .right.> UC_TrocarMensagens : <<extend>>
    UC_ChatDireto .right.> UC_TrocarMensagens : <<extend>>
    UC_AbrirChamado .right.> UC_TrocarMensagens : <<extend>>
    UC_EncerrarChamado .right.> UC_TrocarMensagens : <<extend>>
}



package "Gerenciamento de Reunião e Setores" as P_Reunião {
    usecase (Manter Reunião) as UC_ManterReuniao
    usecase (Visualizar Calendário) as UC_Calendario
    usecase (Manter Setores) as UC_ManterSetores
    usecase (Visualizar Relatório de Departamento) as UC_Relatorio
    usecase (Auditar Histórico Setorial\n- Pesquisa Avançada) as UC_Historico_Departamento

    UC_ManterReuniao .right.> UC_Calendario : <<include>>
    UC_Relatorio .right.> UC_Historico_Departamento : <<include>>
}

' Força o posicionamento vertical dos pacotes para evitar sobreposição
P_Segurança -[hidden]down-> P_Comunicação
P_Comunicação -[hidden]down-> P_Reunião



' Usuário do Sistema (todos herdam)
US --- UC_Login
US --- UC_DefinirSenha 
US --- UC_TrocarMensagens
US --- UC_Calendario


' Usuário Comum
UC --- UC_DefinirSenha
'(essa de definir senha eu não tenho certeza)
UC --- UC_EncerrarChamado
UC --- UC_VisualizarFilas
UC --- UC_Calendario

' Usuário Requerente
UReq --- UC_AbrirChamado

' Gestor
Gestor --- UC_ChatDireto
Gestor --- UC_ManterReuniao
Gestor --- UC_Relatorio
Gestor --- UC_Historico_Departamento


' Administrador
Admin --- UC_GerenciarAcessos
Admin --- UC_RedefinirCredenciais
Admin --- UC_ManterReuniao
Admin --- UC_ManterSetores
Admin --- UC_Auditarlogs

@enduml