@startuml 
' Definição dos Atores e Hierarquia
actor "Usuário do Sistema" as US
actor "Administrador" as Admin
actor "Usuário Comum" as UC
actor "Usuário Requerente" as UReq
actor "Usuário Requerido" as URec
actor "Gestor" as Gestor


US <|-- Admin
US <|-- UC
UC <|-- UReq
UC <|-- URec
UC <|-- Gestor


' Autenticação e Segurança
package "Autenticação e Segurança" {
    usecase (Login) as UC_Login
    usecase (Definir Senha) as UC_DefinirSenha
    usecase (Redefinir Credenciais) as UC_RedefinirCredenciais
    usecase (Gerenciar Acessos) as UC_GerenciarAcessos
    usecase (Vizualizar logs de acesso) as UC_logs
}

' Comunicação 
package "Comunicação" {
    usecase (Trocar Mensagens) as UC_TrocarMensagens
    usecase (Iniciar Chat Direto) as UC_ChatDireto
    usecase (Consultar Histórico de Chats) as UC_Historico
}

' Gerenciamento de Chamados
package "Gerenciamento de Chamados" {
    usecase (Abrir Chamado) as UC_AbrirChamado
    usecase (Visualizar Filas de Chamados) as UC_VisualizarFilas
    usecase (Encerrar Chamado) as UC_EncerrarChamado
    
}

package "Gerenciamento de Reunião e Setores" {
    usecase (Manter Reunião) as UC_ManterReuniao
    usecase (Visualizar Calendário) as UC_Calendario
    usecase (Receber Notificação de Convites) as UC_NotificaConvite
    usecase (Manter Setores) as UC_Setores
    usecase (Visualizar Relatório de Departamento) as UC_Relatorio
    usecase (Auditar Histórico Setorial\n- Pesquisa Avançada) as UC_Historico_Departamento
    usecase (Gerenciar Salas e\nAgendamentos Globais) as UC_GerenciarSalas
}




' Usuário do Sistema (todos herdam)
US --- UC_Login
US --- UC_TrocarMensagens
US --- UC_Calendario
UC_Historico .> UC_TrocarMensagens : <<extend>>

' Usuário Comum
UC --- UC_DefinirSenha 
'(essa de definir senha eu não tenho certeza)
UC --- UC_EncerrarChamado
UC --- UC_VisualizarFilas

' Usuário Requerente
UReq --- UC_AbrirChamado

' Gestor
Gestor --- UC_ChatDireto
Gestor --- UC_ManterReuniao
Gestor --- UC_Relatorio
Gestor --- UC_Historico_Departamento
UC_ChatDireto .> UC_TrocarMensagens : <<extend>>
UC_ManterReuniao <. UC_NotificaConvite: <<extend>>

' Administrador
Admin --- UC_GerenciarAcessos
Admin --- UC_RedefinirCredenciais
Admin --- UC_GerenciarSalas
Admin --- UC_Setores
Admin --- UC_logs

@enduml