name: Exportar PlantUML para PDF

on:
    push:
        branches:
            - main
        paths:
            - "**/*.puml"

jobs:
    render-plantuml:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout do código
              uses: actions/checkout@v4

            - name: Gerar PDF usando imagem oficial com suporte a PDF
              run: |
                  docker run --rm -v ${{ github.workspace }}:/data ghcr.io/schnatterer/plantuml-pdf -tpdf "useCases/diagram/Diagrama_de_Uso(SisCom).puml"
                  docker run --rm -v ${{ github.workspace }}:/data ghcr.io/schnatterer/plantuml-pdf -tpdf "classes/Diagrama_de_Classes.puml"
            - name: Commitar e pushar o PDF de volta para o repositório
              run: |
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"

                  git add "useCases/diagram/Diagrama_de_Uso(SisCom).pdf"
                  git add "classes/Diagrama_de_Classes.pdf"

                  git commit -m "Automação: PDF do PlantUML atualizado" || echo "Sem alterações no diagrama."
                  git push
